/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Common metadata json about a seismogram.
 */
export interface BagExtraHeader {
  y?: Timeseries;
  st?: Station;
  ev?: Event;
  path?: Path;
  mark?: Marker[];
  [k: string]: unknown;
}
/**
 * timeseries amplitude and processing state
 */
export interface Timeseries {
  /**
   * si units of the timeseries amplitude, ex m/s m/s2
   */
  si: string;
  /**
   * basic processing type. Raw is unprocessed, gain has scalar gain/units, corrected transfer of frequency response, processed further userlevel processing
   */
  proc?: "raw" | "gain" | "corrected" | "synth" | "processed";
  [k: string]: unknown;
}
/**
 * receiver station
 */
export interface Station {
  /**
   * latitude in degrees
   */
  la: number;
  /**
   * longitude in degrees
   */
  lo: number;
  /**
   * elevation in meters
   */
  elev?: number;
  /**
   * depth below surface in meters
   */
  dp?: number;
  [k: string]: unknown;
}
/**
 * source earthquake
 */
export interface Event {
  /**
   * public identifier for earthquake
   */
  id?: string;
  origin?: Origin;
  mag?: Magnitude;
  [k: string]: unknown;
}
/**
 * origin, location and time
 */
export interface Origin {
  /**
   * origin time as ISO8601
   */
  time: string;
  /**
   * latitude in degrees
   */
  la: number;
  /**
   * longitude in degrees
   */
  lo: number;
  /**
   * depth in kilometers
   */
  dp: number;
  [k: string]: unknown;
}
/**
 * magnitude
 */
export interface Magnitude {
  /**
   * magnitude value
   */
  val: number;
  /**
   * magnitude type
   */
  type?: string;
  [k: string]: unknown;
}
/**
 * path between source and receiver
 */
export interface Path {
  /**
   * great circle arc distance in degrees, for uses when only distance is needed
   */
  gcarc?: number;
  /**
   * great circle azimuth degrees from event to station, for uses when only distance is needed
   */
  az?: number;
  /**
   * great circle back azimuth in degrees back from station to event, for uses when only distance is needed
   */
  baz?: number;
  [k: string]: unknown;
}
export interface Marker {
  /**
   * marker time as ISO8601
   */
  time: string;
  name: string;
  amp?: number;
  [k: string]: unknown;
}
